version: '2'
services:
    api:
        build: .
        env_file:
            - ./.environment/.public.env
            - ./.environment/.private.env
        links:
            - database
        ports:
            - "3000:3000"
        depends_on:
            - database
        volumes:
            - ./:/api

    database:
        image: postgres
        env_file:
            - ./.environment/.public.env
            - ./.environment/.private.env
        ports:
            - "5432:5432"
