version: '2'
services:
    api:
        build: .
        env_file:
            - ./.environment/.public.env
            - ./.environment/.private.env
        links:
            - database
        ports:
            - "3000:3000"
        depends_on:
            - database

    database:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - storage:/var/lib/postgresql/data

volumes:
    storage:
        driver: local
