version: '2'
services:
    api:
        build: .
        env_file:
            - ./.environment/public.env
            - ./.environment/private.env
        links:
            - "database"
        ports:
            - "3000:3000"
        volumes:
            - ./app/:/api/app
            - ./config:/api/config
            - ./database:/api/database
        depends_on:
            - database

    database:
        image: postgres
        env_file:
            - ./.environment/public.env
            - ./.environment/private.env
        ports:
            - "5432:5432"
        volumes:
            - storage:/var/lib/postgresql/data

volumes:
    storage:
        driver: local
