version: '2'
services:
    api:
        build: .
        env_file:
            - ./.environment/.public.env
            - ./.environment/.private.env
        links:
            - database
        ports:
            - "3000:3000"
        volumes:
            - ./:/api

    database:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - storage:/data/db

volumes:
    storage:
